# Generated by Django 6.0.4 on 2026-04-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
